eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign

---
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
